@startuml

class ScreenConnector<ProcessedFrameType> {
  -sc_android_src_: WaylandScreenConnector
  -host_mode_ctrl_: HostModeCtrl
  -on_next_frame_cnt_: unsigned long long int
  -render_confui_cnt_: unsigned long long int
  -sc_frame_multiplexer_: FrameMultiplexer
  -callback_from_streamer_: GenerateProcessedFrameCallback
  -streamer_callback_mutex_: std::mutex
  -streamer_callback_set_cv_: std::condition_variable
  +ScreenConnector(<color:LightSlateGray>WaylandScreenConnector&, HostModeCtrl&</color>)
  +SetCallback(<color:LightSlateGray>frame_callback: GenerateProcessedFrameCallback&&</color>)
  +IsCallbackSet() const
  +SetDisplayEventCallback(<color:LightSlateGray>event_callback: DisplayEventCallback</color>)
  +OnNextFrame()
  +RenderConfirmationUi(<color:LightSlateGray>uint32_t, uint32_t, uint32_t, uint32_t,std::uint8_t*</color>)
}

class ScreenConnectorInputMultiplexer<ProcessedFrameType> {
  - host_mode_ctrl_: HostModeCtrl
  - multiplexer_: Multiplexer<ProcessedFrameType, Queue>
  - on_next_frame_cnt_: unsigned long long int
  - sc_android_queue_id_: int
  - sc_confui_queue_id_: int
  + PushToAndroidQueue(<color:LightSlateGray>item: ProcessedFrameType</color>)
  + PushToConfUiQueue(<color:LightSlateGray>item: ProcessedFrameType</color>)
  + Pop(): ProcessedFrameType
}
note top of ScreenConnectorInputMultiplexer: Combines Android and ConfUI frames\nto Stream everything to a user as a single picture

class WaylandScreenConnector {
  -server_: WaylandServer*
  +WaylandScreenConnector(<color:LightSlateGray>ANNOTATED(FramesFd, int) frames_fd</color>)
  +SetFrameCallback(<color:LightSlateGray>frame_callback: GenerateProcessedFrameCallbackImpl</color>)
  +SetDisplayEventCallback(<color:LightSlateGray>event_callback: DisplayEventCallback</color>)
}

ScreenConnector *-- ScreenConnectorInputMultiplexer : referred as FrameMultiplexer >
ScreenConnector *-- WaylandScreenConnector : sets GenerateProcessedFrameCallbackImpl\nand DisplayEventCallback >

DisplayHandler *-- ScreenConnector : sets GenerateProcessedFrameCallbackImpl\nand DisplayEventCallback >

WaylandScreenConnector *-- WaylandServer : sets GenerateProcessedFrameCallbackImpl\nand DisplayEventCallback >

@enduml
